### PR TITLE
Fix compatibility issues with jsonschema>=4

### PR DESCRIPTION
**Pull request by aaneto**
I have managed to pass the tests after updating jsonschema. The only issue I have is that Python 3.6 is having dependency issues with jsonschema==4.

I'll try to make the changes compatible with both jsonschema4 and 3, so that Python3.6 is still compatible.

### CODE REVIEW

**Review by wRAR — APPROVED** [review]

**Comment by aaneto** [comment]
I don't believe I see anything else that needs doing, I'll remove the WIP tag so that others can give feedback more freely.

**Review by Gallaecio — APPROVED** [review]
Looks good to me.

I do wonder if we should implement a test job that uses the minimum supported versions of stuff, like we do in Scrapy, to make sure we do not break backward compatibility with older jsonschema as we add support for newer ones.

**Comment by aaneto** [comment]
Great :)

If I'm not mistaken all that we need now is for someone with merge permission to accept this PR, correct?

**Comment by Gallaecio** [comment]
> I do wonder if we should implement a test job that uses the minimum supported versions of stuff, like we do in Scrapy, to make sure we do not break backward compatibility with older jsonschema as we add support for newer ones.

Let me implement this, then we can merge.

**Comment by Gallaecio** [comment]
Thanks!

**Comment by aaneto** [comment]
Oh, sorry! That's what you meant by testing job, I thought it was a job on a cloud or something like that.

In any case, thanks everyone! :)

**Pull request merged**
