### PR TITLE
Fix tests for minimum properties and items

### PR DESCRIPTION
**Pull request by rochamatcomp**
In JSON Schema validation for minimum properties and items the data should be non-empty, then I changed the minimum properties e items configuration to 2. To test empty cases as invalid I create corresponding tests.

I fixed some simples warnings such as warning from pytest trylast and about literal comparations with 'is'.

### CODE REVIEW

**Comment by rochamatcomp** [comment]
The pipeline for python 3.8 has jsonschema==3.2.0, for other versions it has jsonschema>=3.2.0 (at present 4.21.1). The old version of JSON Schema allows valid empty properties and items, contrary to latest versions.

Can we change jsonschema version in tox.ini like this?
```
[testenv:min]
basepython = python3.8
deps =
    {[testenv]deps}
    jsonschema[format]>=3.2.0
```

**Comment by VMRuiz** [comment]
> The pipeline for python 3.8 has jsonschema==3.2.0, for other versions it has jsonschema>=3.2.0 (at present 4.21.1). The old version of JSON Schema allows valid empty properties and items, contrary to latest versions.
> 
> Can we change jsonschema version in tox.ini like this?
> 
> ```
> [testenv:min]
> basepython = python3.8
> deps =
>     {[testenv]deps}
>     jsonschema[format]>=3.2.0
> ```

The reason for that test suite is to run the tests with the minimum valid package version, so it must be `==` not `>=`. However, we can increase the minimum required version for jsonschema to the lowest version that passes the new tests. 

Please make sure to update setup.py too:

```
# tox.ini
[testenv:min]
basepython = python3.8
deps =
     {[testenv]deps}
     jsonschema[format]>=x.x.x
     
# setup.py
install_requires=[
        "jsonschema[format]>=x.x.x",
 ```
 
 Thank you so much for your interest in this project!

**Comment by rochamatcomp** [comment]
@VMRuiz thanks for your explanation! Until version 4.20.0 (included) the behaviour is the same of version 3.2.0. JSON Schema validation for minimum properties and items has recently changed from version 4.21.0 (at present the latest is 4.21.1).

Can we use the following configuration?

```
 # tox.ini
[testenv:min]
basepython = python3.8
deps =
     {[testenv]deps}
     jsonschema[format]==4.21.0
     
# setup.py
install_requires=[
        "jsonschema[format]>=4.21.0",
```

**Comment by VMRuiz** [comment]
> @VMRuiz thanks for your explanation! Until version 4.20.0 (included) the behaviour is the same of version 3.2.0. JSON Schema validation for minimum properties and items has recently changed from version 4.21.0 (at present the latest is 4.21.1).
> 
> Can we use the following configuration?
> 
> ```
>  # tox.ini
> [testenv:min]
> basepython = python3.8
> deps =
>      {[testenv]deps}
>      jsonschema[format]==4.21.0
>      
> # setup.py
> install_requires=[
>         "jsonschema[format]>=4.21.0",
> ```

Yes, please go ahead an introduce these changes in your PR

**Review by VMRuiz — APPROVED** [review]

**Comment by VMRuiz** [comment]
Merged, thanks for you work @rochamatcomp

**Pull request merged**
