### PR TITLE
Update and rename CONTRIBUTING.rst to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by manycoding**
I translated the file to .md to make it visible in github UI https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Good change, this would help in people making PR's for the first time to Spidermon. LGTM.

**Comment by rennerocha** [comment]
Files in reStructuredText format appears correctly in Github UI, so it is an unnecessary change, considering that all other docs we have are in RST. Let's keep all our docs in RST.

**Comment by manycoding** [comment]
@Gallaecio @rennerocha 
I wasn't clear enough, the reason of this pr is that contribution tooltip will be shown. RST is rendered correctly, but this tooltip on the right is visible only for MD - 
Screenshot 2019-04-26 at 11 47 17

**Comment by rennerocha** [comment]
I don't think that renaming it, just to have access to a tiny link, in a sidebar, where it is very likely that the majority of the people opening issues won't notice justify the use two different formats (markdown and RST) for project docs.

**Comment by manycoding** [comment]
I don't see it as project docs - for me they live only in docs/ folder. Everything else - readme, contributions, license - are repo files\docs.
But I see your point.

**Comment by Gallaecio** [comment]
I was not clear enough either: we already get that contribution tooltip with RST:

Screenshot_20190429_083306

**Comment by manycoding** [comment]
@Gallaecio I didn't expect, cool. I still don't like rst though :)

**Pull request closed without merging**
