### PR TITLE
Add Discord integration

### PR DESCRIPTION
**Pull request by anapaulagomes**
Add Discord integration. To test it you'll need two environment variables: `SPIDERMON_DISCORD_WEBHOOK_URL` and `SPIDERMON_DISCORD_FAKE`. See how to get a discord webhook URL [here](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks).

Checklist:

- [x] Add Discord integration
- [x] Add tests
- [x] Add docs

### CODE REVIEW

**Comment by anapaulagomes** [comment]
The build is failing due to a formatting issue that isn't related to this PR. How should I  proceed?

**Comment by anapaulagomes** [comment]
Any news here @rennerocha?

**Comment by netoferraz** [comment]
Hey guys, this PR could add a very useful feature to this project. There are any intention to accept this suggestion for the project?

**Comment by rennerocha** [comment]
Yes, we want this PR to be merged as soon as possible. Probably it will be available in our next release.

**Review by further-reading — CHANGES_REQUESTED** [review]
I've updated it the latest master branch and reran the workflow. I like the approach of using requests.post with a webhook instead of the discord package - I think we could one day expand on this to make a generic "send API request" notifier since all we need is a uri, token + body.

codecov is reporting some additional coverage needed to unit tests. Once these are in I should be able to approve + merge.

**Comment by rennerocha** [comment]
This feature will be finished in https://github.com/scrapinghub/spidermon/pull/348

**Pull request closed without merging**
