### PR TITLE
docs: Mixins documentation

### PR DESCRIPTION
**Pull request by gcmurillo**
Adding docs for mixin objects in `spidermincontrib/monitors/mixins`

### CODE REVIEW

**Comment by gcmurillo** [comment]
Issue #84

**Comment by gcmurillo** [comment]
Well, there is not sources where I can get information for this objects. I did a description with a general purpose review for each one. I will get your suggestion and put the code in the docs too.

**Comment by rennerocha** [comment]
@gcmurillo do you plan to continue working on this issue?

**Comment by rennerocha** [comment]
As the last activity in this PR was in May, I am closing it in favor of https://github.com/scrapinghub/spidermon/pull/232

**Pull request closed without merging**
