### PR TITLE
Any color you like

### PR DESCRIPTION
**Pull request by manycoding**
#91 
I didn't exclude any files, but it looks right. I kind of want to separate **requirements.txt** from the **tox.ini** too and use **setup.py** `extras`, but I am not sure if it belongs to this pr.

Last but not least, `pep8` section in tox doesn't really need all requirements, but I am not sure how to avoid default ones in `testenv`.

### CODE REVIEW

**Comment by manycoding** [comment]
I left the commit history as a good lesson (for me atleast).

**Comment by manycoding** [comment]
Closes #91

**Comment by raphapassini** [comment]
Hey @manycoding nice initiative :)
I have a main concern that is the PR is enormous :(, 91 files changes are a lot to review. 
Maybe we can add the black in a PR and then _apply_ the black in another PR. I looked in the PR and it seems OK, but we are changing a lot of files there. I would like to hear other comments here

**Comment by manycoding** [comment]
@raphapassini It makes more sense to apply Black first, and then add it since the only changes are about CI.

**Comment by manycoding** [comment]
Closed in fabor of separated pr

**Pull request closed without merging**
