### PR TITLE
Any colour you like

### PR DESCRIPTION
**Pull request by manycoding**
#91 
As per https://github.com/scrapinghub/spidermon/pull/92#issuecomment-464754628
This commit adds Black and CI setup

@raphapassini

### CODE REVIEW

**Comment by raphapassini** [comment]
+1 to merge

**Comment by rennerocha** [comment]
I understand what we want to accomplish but I didn't understand what this PR will do.

The build will fail if the following command lists files that needs to be changed? 
`black ./ --check --diff`

**Comment by manycoding** [comment]
@rennerocha Yes. That's a good way to ensure the uniform style. I preformatted the files in another pr, so it won't fail after merge.
Basically `black  ./ --check --diff` is the same as `flake .`

**Comment by rennerocha** [comment]
@manycoding thanks for the explanation :-)

**Pull request merged**
