### PR TITLE
Apply black

### PR DESCRIPTION
**Pull request by manycoding**
Apply changes first,
#92 

As per #91, this pull request only formats files with black.

### CODE REVIEW

**Comment by manycoding** [comment]
https://github.com/scrapinghub/spidermon/pull/92#issuecomment-464754628
@raphapassini

**Comment by raphapassini** [comment]
@manycoding after fixing the the conflicts +1 to merge.

**Comment by manycoding** [comment]
@raphapassini @rennerocha I pray to gods that nobody merges to master before this one is closed.

**Comment by rennerocha** [comment]
@manycoding I suggest you update this branch with master, as it was updated in the latest days.
I will not merge anything else until this branch is merged.

**Comment by manycoding** [comment]
@rennerocha I merged the master 3 times, it's just I forgot to test the latest merge.
If there will be yet another merge before this one is closed, I will have an acute merge intoxication.

**Comment by rennerocha** [comment]
> @rennerocha I merged the master 3 times, it's just I forgot to test the latest merge.
> If there will be yet another merge before this one is closed, I will have an acute merge intoxication.

Don't worry! There will not be another merge to master before this :-)

**Comment by manycoding** [comment]
Now I can sleep safely at night without having merge nightmares.

**Pull request merged**
